###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = "Henrik Finsberg"
bibtex_bibfiles = ["docs/refs.bib"]
codeautolink_concat_default = True
comments_config = {"hypothesis": False, "utterances": False}
copyright = "2025"
exclude_patterns = [
    "**.ipynb_checkpoints",
    ".DS_Store",
    ".github/*",
    ".pytest_cache/*",
    ".tox/*",
    "Thumbs.db",
    "_build",
    "third_party/*",
    "jupyter_execute/",
    "**.jupyter_cache",
]
extensions = [
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "myst_nb",
    "sphinx_comments",
    "sphinx_external_toc",
    "sphinx.ext.intersphinx",
    "sphinx_design",
    "sphinx_book_theme",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
    "sphinx_codeautolink",
    "sphinx_multitoc_numbering",
]
external_toc_exclude_missing = True
external_toc_path = "_toc.yml"
html_baseurl = ""
html_favicon = ""
html_last_updated_fmt = "%b %d, %Y"
html_logo = "docs/logo.png"
html_sourcelink_suffix = ""
html_static_path = ["_static"]
html_theme = "sphinx_book_theme"
html_theme_options = {
    "search_bar_text": "Search this book...",
    "launch_buttons": {
        "notebook_interface": "classic",
        "binderhub_url": "",
        "jupyterhub_url": "",
        "thebe": False,
        "colab_url": "",
        "deepnote_url": "",
    },
    "path_to_docs": "",
    "repository_url": "https://github.com/finsberg/fenicsx-pulse",
    "repository_branch": "main",
    "extra_footer": "",
    "home_page_in_toc": True,
    "announcement": "",
    "analytics": {
        "google_analytics_id": "",
        "plausible_analytics_domain": "",
        "plausible_analytics_url": "https://plausible.io/js/script.js",
    },
    "use_repository_button": True,
    "use_edit_page_button": False,
    "use_issues_button": True,
}
html_title = "fenicsx-pulse"
intersphinx_mapping = {
    "basix": ["https://docs.fenicsproject.org/basix/main/python/", None],
    "ffcx": ["https://docs.fenicsproject.org/ffcx/main/", None],
    "ufl": ["https://docs.fenicsproject.org/ufl/main/", None],
    "dolfinx": ["https://docs.fenicsproject.org/dolfinx/main/python", None],
    "petsc4py": ["https://petsc.org/release/petsc4py", None],
    "mpi4py": ["https://mpi4py.readthedocs.io/en/stable", None],
    "numpy": ["https://numpy.org/doc/stable/", None],
    "matplotlib": ["https://matplotlib.org/stable/", None],
    "pyvista": ["https://docs.pyvista.org/", None],
    "packaging": ["https://packaging.pypa.io/en/stable/", None],
    "gotranx": ["https://finsberg.github.io/gotranx/", None],
    "cardiac_geometries": ["https://computationalphysiology.github.io/cardiac-geometriesx/", None],
}
latex_engine = "pdflatex"
myst_enable_extensions = ["amsmath", "dollarmath", "linkify"]
myst_url_schemes = ["mailto", "http", "https"]
nb_custom_formats = {".py": ["jupytext.reads", {"fmt": "py"}]}
nb_execution_allow_errors = False
nb_execution_cache_path = ""
nb_execution_excludepatterns: list[str] = []
nb_execution_in_temp = False
nb_execution_mode = "cache"
nb_execution_show_tb = True
nb_execution_timeout = 3000
nb_output_stderr = "show"
numfig = True
pygments_style = "sphinx"
suppress_warnings = ["mystnb.unknown_mime_type", "bibtex.duplicate_citation"]
use_jupyterbook_latex = True
use_multitoc_numbering = True
